version: 0.2

env:
  parameter-store:
    TASK_LIST_URI: /CodeBuild/TaskList/Prod/taskListUri
    TASK_LIST_PORT: /CodeBuild/TaskList/Prod/taskListPort
    TASK_LIST_INTERNAL_PORT: /CodeBuild/TaskList/Prod/taskListInternalPort
    TASK_LIST_MONGO_CONNECTION_STRING: /CodeBuild/TaskList/Prod/mongoConnectionString
    TASK_LIST_OAUTH_CLIENT_ID: /CodeBuild/TaskList/Prod/oauthClientId
    TASK_LIST_OAUTH_CLIENT_SECRET: /CodeBuild/TaskList/Prod/oauthClientSecret
    TASK_LIST_SESSION_SECRET: /CodeBuild/TaskList/Prod/sessionSecret

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
      - npm --prefix ../todo-ui install
      - node ../todo-ui/writeconfig.js ../todo-ui/config/prod.json
      - node writeconfig.js ./config/production.json
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm --prefix ../todo-ui run build
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

